### ISSUE TITLE
172.28.1.211 is a reserved IP address

### ISSUE THREAD

**Issue by CNMan** [Narizgnaw/needtobebanned#2]
用ip2location的工具批量查询IP归属地的时候发现这一条有误
https://www.ip2location.com/free/applications
https://en.wikipedia.org/wiki/Reserved_IP_addresses

**Comment by Narizgnaw** [comment]
感谢反馈，我找时间研究下这是如何出现的。

**Comment by Narizgnaw** [comment]
研究了半天没研究出来这个172.28.1.211是怎么来的，先删掉了，没准是公有云系统后门啥的……
